### PR TITLE
Upgrade project to .NET 6

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
I did some quick tests and so far it seems to run fine. Feel free to do your own, but I think it's worth it as you keep working on it.

### CODE REVIEW

**Review by LaZar00 — APPROVED** [review]

**Comment by LaZar00** [comment]
Let's try then NET 6.0. The think that I fear most is the HighDPI aware useless and stupidity thing Windows has.

**Comment by julianxhokaxhiu** [comment]
That got automatically added by the upgrader, feel free to comment that part if it brings more issues than benefits :)

**Comment by LaZar00** [comment]
Right now the issue I have is that I'm using VS 2019 and I should upgrade to VS 2022 to make .NET 6 work. It is not compatible with VS 2019. And really, I don't want to install VS 2022. At least, not yet, sorry. And I don't know which could be the benefits... compatibitility with other OSs?

I have reverted back the change to .NET Framework 4.7.2.

If in the future MS decides to make .NET 6 compatible with VS 2019 I am disposed to migrate to .NET 6. But if not, I prefer to leave it as is.

**Comment by julianxhokaxhiu** [comment]
Not sure why you are against VS2022 to be honest, by compatibility wise it's the same as .NET 4.7.2 but with just better performance on top and newer C# language support.

**Comment by LaZar00** [comment]
Oh. I'm not against VS2022. But I think it is too young that's all.
Apart:
- Now I have a VS2019 environment where I can practice my hobby (programming). Upgrade to VS2022 means to test the things I've done or even investigate if some things will work or not. I don't want to lose the time with this right now. Probably all works well... but who knows.
- VS2022 means to adapt to another way of working, surely they have changed some UI things or other internals. This is more time I had to invest in learning it. And now I have not that time.
- .NET 6 had its preview release for VS2019. Why there is not a final release for VS2019? You are bound to use VS2022 yes or yes if you want to use .NET 6. I should not be bound to any development software to make use of something (and this is my point of view).

Well, as you can see I have some reasons to not use right now VS2022 and .NET 6. Maybe in 1-2 years I'm more confident in use them.

EDIT: Let's do one thing. I've seen you can have both environments 2019/2022. When I have a bit of time I will install 2022 and I will be able to do some test. But this will take some time.

**Comment by julianxhokaxhiu** [comment]
All right, no worries :) I'm personally using VS2022 to work on 7th and i didn't notice anything different from VS2019, but up to you when and if you want to start using it. You have the upgrade commit anyway on your own side in case you feel you want to move it back to .NET 6. Feel free to ping me otherwise and I'll be happy to help. Cheers!

**Pull request merged**
